import type { Metadata } from "next";
import { Varela_Round } from 'next/font/google';
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider, SignedIn } from '@clerk/nextjs';
import Navbar from "@/components/navbar/navigation-menu";
import { ThemeProvider } from "@/components/theme-provider";

const varelaRound = Varela_Round({
  subsets:['latin'],
  weight:"400"
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${varelaRound.className} antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
          <SignedIn>
            <Navbar></Navbar>
          </SignedIn>
            {children}
        </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
